- CHANGELOG.md
- README.md
- src/router.js
- test/router.spec.js
> add query option to navigate

- package-lock.json
- package.json
- types/raviger.d.ts
fixes #12 
currently published on `beta` tag
install with `npm i raviger@beta` or `npm i raviger@0.5.1-beta.1`
> add type declaration

- package-lock.json
- package.json
- types/raviger.d.ts
typescript types published with repo. Published under the `beta` tag. To try them out, install with
```
npm install raviger@beta
```
or, the current beta with
```
npm install raviger@0.5.4-beta.1
```
> typescript types

- src/navigate.js
Finally got around to fixing this and merging to master. The type checking now takes into account `null` and `typeof` returning `object` when the variable is an array. The tests are now passing on my end.
> Navigation - More Robust Type Checking

- README.md
move non-quickstart docs out of README into docs site
> update readme for docs site

- CHANGELOG.md
- src/Link.js
- test/Link.spec.js
> dont trap Link on target=_blank

- src/path.js
- src/querystring.js
- src/router.js
- test/path.spec.js
> memozie useLocationChange with useRef

- package.json
- rollup.config.js
- src/path.js
see [this comment](https://github.com/kyeotic/raviger/pull/32#discussion_r343980449) for details
> Use initial value for setRef

- CHANGELOG.md
- docs/content/api/Link.md
- src/Link.js
- src/querystring.js
- test/Link.spec.js
- test/querystring.spec.js
- types/raviger.d.ts
> add Link.basePath

- docs/content/api/Redirect.md
- docs/content/api/useHash.md
- example/src/App.js
- package-lock.json
- package.json
- src/main.js
- src/path.js
- src/redirect.js
- test/context.spec.js
- test/path.spec.js
- test/redirect.spec.js
- types/raviger.d.ts
Adds new `<Redirect>` component and `useHash` hook
> Add Redirect and useHash

- CHANGELOG.md
- example/src/NestedApp.js
- example/src/index.js
- package-lock.json
- package.json
- src/path.js
- test/path.spec.js
This should fix #50 
I tried to verify this, but I don't have time to fully vet it tonight but I want to unblock @macku so I am publishing under the `beta` tag
```
npm i raviger@beta
OR
npm i raviger@1.4.1-0
```
I will vet tomorrow and release on proper if it looks good.
> Nested use path

- .gitignore
- Makefile
- src/router.js
- test/router.spec.js
> Macku fix hooks deps

- types/raviger.d.ts
> Fix TS declaration of useNavigationPrompt function

- CHANGELOG.md
- src/path.js
- test/router.spec.js
> fix case insensitive matching for basePath

- CHANGELOG.md
- example/src/App.js
- example/src/index.js
- src/navigate.js
- test/navigate.spec.js
This addresses the issue originally raised in #62
> Fix `replace` handling on `navigate`

- docs/content/api/Redirect.md
- jest.config.js
- package-lock.json
- package.json
- src/querystring.js
- src/redirect.js
- test/querystring.spec.js
- test/redirect.spec.js
- test/setup.js
- types/raviger.d.ts
> add "query" option to redirect component

- CHANGELOG.md
- src/router.js
- test/router.spec.js
> special case '/' when matchTrailingSlash is set

- CHANGELOG.md
- package-lock.json
- package.json
- src/navigate.js
- types/raviger.d.ts
adds a `state` parameter option to `navigate`
#82 
Available for pre-release testing
```
npm i raviger@beta
npm i raviger@2.0.2-0
```
> Navigate state

- CHANGELOG.md
- docs/api/useLocationChange.md
- src/hooks.js
- src/path.js
- test/path.spec.js
> default useLocationChange to skip initial render

- CHANGELOG.md
- src/intercept.js
- src/navigate.js
- src/path.js
- test/navigate.spec.js
> add support for back/forward interception

- CHANGELOG.md
- example/src/App2.js
- example/src/index.js
- package-lock.json
- src/path.js
- src/redirect.js
- src/router.js
- test/redirect.spec.js
closes #84
This is hacky, but it works.
The root of the issue is that `<Redirect />` causes a change to the path state _after_ `useRoutes` has returned, but before the render loop has finished. `usePath` and `useLocationChange` both fire, but React appears to suppress the re-render that this should cause, even though its from a `useLayoutEffect`. I'm sure there is a better way to do this, but I don't know how.
> handle <redirect> in useRoutes

- src/Link.tsx
- test/Link.spec.tsx
> fix(): ActiveLink classes

- docs/api/ActiveLink.md
- docs/api/Redirect.md
- docs/api/useLocationChange.md
- docs/api/useQueryParams.md
- docs/api/useRoutes.md
various doc typos and clarifications
> Docs patch

- package.json
- yarn.lock
> feat: add react 18 support

- docs/api/useHistory.md
> docs: add useHistory
